name: Linux (Vulkan)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt install make clang libvulkan-dev libgtk-3-dev --yes --quiet
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
    - name: Upload artifact (all)
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-linux
        path: paint/build/out/
        if-no-files-found: error
    - name: Upload artifact (executable only)
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-linux-exe
        path: paint/build/out/ArmorPaint
        if-no-files-found: error
