name: macOS (Metal)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-macos
        path: paint/build/Release/
        if-no-files-found: error
