name: Windows (Direct3D12)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
    - name: Upload artifact (all)
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-windows
        path: paint/build/out/
        if-no-files-found: error
    - name: Upload artifact (executable only)
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-windows-exe
        path: paint/build/out/ArmorPaint.exe
        if-no-files-found: error
